project:
  type: website
  output-dir: _site  # <- dÃ©placer ici

website:
  title: "Massif Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
